---
title: "August Low Flow"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dataRetrieval)
library(ggplot2)
```

```{r basics,include=FALSE}
start_date <- '1999-10-01'
end_date <- '2019-09-30'
```

```{r function creation, include=FALSE}
ALF_mins <- function(site_id,start_date,end_date) {
  # first calculate min flow of each august year then find median
  #import data
  flow <- readNWISdv(site_id,'00060',start_date,end_date)
  # add the month and water year column
  date <- flow$Date
  month <- format(as.Date(date,format = '%d-%m-%Y'), '%m')
  month <- as.numeric(month)
  flow$month <- month
  flow <- addWaterYear(flow)
  #initialize mins_ap vector
  aug_mins <- c()
  w_year <- flow$waterYear[1]
  # Now evaluate
  while (w_year <= 2019) {
    w_year <- toString(w_year)
    aug <- flow[(flow$waterYear == w_year) & (flow$month == 8), ]
    min_val <- min(aug$X_00060_00003)
    aug_mins <- append(aug_mins, min_val)
    w_year <- strtoi(w_year) + 1
  }
  median_min <- median(aug_mins)
  return(aug_mins)
}
```
## Site 02040000: Appomattox River

```{r appomattox, echo=FALSE}
# first calculate min flow of each august year then find median
#import data
mins_ap <- ALF_mins('02040000',start_date,end_date)
median_ap <- median(mins_ap)

ggplot(data.frame(mins_ap), aes(x = "", y = mins_ap)) + geom_boxplot() + theme_bw() +
  labs(y='Discharge [cfs]', x='August Low Flows',title= 'Appomattox River August Low Flows') 
cat('The August low flow value is', median_ap)

```

## Site 02047500
```{r blackwater river, echo=FALSE}
mins_bl <- ALF_mins('02047500',start_date,end_date)
median_bl <- median(mins_bl)
ggplot(data.frame(mins_bl), aes(x = "", y = mins_bl)) + geom_boxplot() + theme_bw() +
  labs(y='Discharge [cfs]', x='August Low Flows',title= 'Blackwater River August Low Flows') 

cat('The August low flow value is', median_bl)

```


## Site 01626000
```{r south river, echo=FALSE}
mins_so <- ALF_mins('01626000',start_date,end_date)
median_so <- median(mins_so)
ggplot(data.frame(mins_so), aes(x = "", y = mins_so)) + geom_boxplot() + theme_bw() +
  labs(y='Discharge [cfs]', x='August Low Flows',title= 'South River August Low Flows') 

cat('The August low flow value is', median_so)

```

## Site 01646502
```{r potomac river, echo=FALSE}
mins_pt <- ALF_mins('01646502',start_date,end_date)
median_pt <- median(mins_pt)
ggplot(data.frame(mins_pt), aes(x = "", y = mins_pt)) + geom_boxplot() + theme_bw() +
  labs(y='Discharge [cfs]', x='August Low Flows',title= 'Potomac River August Low Flows') 

cat('The August low flow value is', median_pt)

```

## Site 03473000
```{r holston river, echo=FALSE}
mins_hl <- ALF_mins('03473000',start_date,end_date)
median_hl <- median(mins_hl)
ggplot(data.frame(mins_hl), aes(x = "", y = mins_hl)) + geom_boxplot() + theme_bw() +
  labs(y='Discharge [cfs]', x='August Low Flows',title= 'Holston River August Low Flows') 

cat('The August low flow value is', median_hl)

```
