#' Time Series data object
#' @description Object for storing single time series value
#' @details Has standard methods for managing data and meta data
#' @importFrom R6 R6Class  
#' @param datasource optional RomDataSource for remote and local storage
#' @param config list of attributes to set
#' @return reference class of type openmi.om.base.
#' @seealso NA
#' @examples NA
#' @export RomTS
RomTS <- R6Class(
  "RomTS",
  public = list(
    #' @field tid unique ID in this RomDataSource
    tid = NULL,
    #' @field featureid id of entity this is attached to
    featureid = NULL,
    #' @field entity_type type of entity this is attached to
    entity_type = NULL,
    #' @field tstime begin timestamp
    tstime = NULL,
    #' @field tsendtime end time stamp
    tsendtime = NULL,
    #' @field tsvalue numerical value
    tsvalue = NULL,
    #' @field tscode alphanumerical value
    tscode = NULL,
    #' @field tlid timeline ID (for future use)
    tlid = NULL,
    #' @field varid variable ID from RomDataSource
    varid = NULL,
    #' @field bundle (for future use)
    bundle = NULL,
    #' @field uid user id of creator
    uid = NULL,
    #' @field datasource RomDataSource
    datasource = NULL,
    #' @param site URL of some RESTful repository
    #' @param config list of attributes to set, see also: to_list() for format
    #' @return object instance
    initialize = function(datasource = NULL, config = list()) {
      # a config template can be generated by using the to_list() method 
      # of a blank object
      # todo: some of this can be handled by the RomDataSource?
      stopifnot(class(datasource)[[1]] == "RomDataSource")
      self$datasource <- datasource 
      config_cols <- names(config)
      if (is.element("varkey", config_cols)) {
        if (!is.null(self$datasource)) {
          config$varid = self$datasource$get_vardef(config$varkey)
        }
      }
      self$from_list(config)
    },
    #' @param config list of attributes to set, see also: to_list() for format
    #' @return NULL
    from_list = function(config) {
      for (i in names(config)) {
        if (i == "tid") {
          self$tid = config$tid
        } else if (i == "varid") {
          self$varid = config$varid
        } else if (i == "entity_type") {
          self$entity_type = config$entity_type
        } else if (i == "featureid") {
          self$featureid = config$featureid
        } else if (i == "tstime") {
          self$tstime = config$tstime
        } else if (i == "tsendtime") {
          self$tsendtime = config$tsendtime
        } else if (i == "tsvalue") {
          self$tsvalue = config$tsvalue
        } else if (i == "tscode") {
          self$tscode = config$tscode
        } else if (i == "tlid") {
          self$tlid = config$tlid
        } else if (i == "bundle") {
          self$bundle = config$bundle
        }
      }
    },
    #' @return list of object attributes suitable for input to new() and from_list() methods
    to_list = function() {
      # returns as a list, which can be set and fed back to 
      # from_list() or new(config)
      t_list <- list(
        tid = self$tid,
        varid = self$varid,
        entity_type = self$entity_type,
        featureid = self$featureid,
        tstime = self$tstime,
        tsendtime = self$tsendtime,
        tsvalue = self$tsvalue,
        tscode = self$tscode,
        tlid = self$tlid,
        bundle = self$bundle
      )
      return(t_list)
    },
    #' @param name attribute name
    #' @param value attribute value
    #' @param format type of data being sent (default, json, ...)
    #' @return object instance
    set_prop = function(name, value, format='default') {
      # this should be at the base class, should not have to subclass
      # @tbd: can this even be done on a local object field? 
      # it may not be necessary, we may only implement 
      # calls to set RomProperties linked to it?
      # self$hair <- val
    }
  )
)


